[package]
name = "socket-fd-ext"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { version = "0.2" }
tokio = { version = "1.48", features = ["net"] }
tracing = { version = "0.1", optional = true }

[features]
tracing = ["dep:tracing"]
