[package]
name = "one-true-pairing"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
wayland-client = { version = "0.31" }
zbus = { version = "5.12" }
