[package]
name = "whale-land"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { version = "0.1" }
socket-fd-ext = { path = "../socket-fd-ext", features = ["tracing"] }
tokio = { version = "1.48", features = ["net"] }
tracing = { version = "0.1" }
